### ISSUE TITLE
preview: pdf previewer not working in local mode

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/cookiecutter-invenio-rdm#49]
Due to ``The resource from “https://localhost:5000/static/js/pdfjs/pdf.worker.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).``

Also getting: ``Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'``

**Comment by fenekku** [comment]
I wasn't able to reproduce the pdf previewer not working part. 

`pdf.worker.min.js` is indeed missing, but it's not breaking the previewer so far as we can tell. There is an issue for this here: https://github.com/inveniosoftware/invenio-previewer/issues/109. Both in `containerize` and `run`, pdfs and images worked fine for me.

Is it with S3?

Otherwise we can close (must have been fixed at some point).

**Comment by ppanero** [comment]
I wasn't able to reproduce it now. Sorry for the noise.
