### ISSUE TITLE
Re-use asset building script in Dockerfile

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/cookiecutter-invenio-rdm#8]
Let's try to reuse `bootstrap.sh` in the Dockerfile to avoid multiple asset generation code. This gets confusing and out of sync quickly has been my experience.

**Comment by ppanero** [comment]
I think the idea is to not have any scripts, and perform all actions from the CLI. In the next release we should move all those to `invenio-cli`. Some reasons I can think about are:

- Easier upgrade, its quite difficult to upgrade scripts, people might have their custom code there...
- If we do all programatically we have more control over what happens and code will be cleaner (e.g. this issue would not exists, since we probably would only have one function for such functionality)
- See also: https://github.com/inveniosoftware/invenio-cli/issues/24

I'd vote to open an issue in invenio-cli such as *move all scripts content to cli python code* and close this one. What do you think?

**Comment by fenekku** [comment]
Moving all scripts to one location (`invenio-cli`) sounds good to me. The process would then be for the developer:

1- install `invenio-cli`
2- use that to setup  the assets
3- use that to build the images which would copy the above generated assets

We will just have to be clear on the order of commands.

**Comment by ppanero** [comment]
Perfect. AFAIK Invenio in general wants to get away of bash scripts cuz they are messy to keep up to date without forcing users to "pull" again a repo (which is not the idea).

Closing this ticket? I can create a new one to "migrate scripts to code"

**Comment by fenekku** [comment]
Good for closing and creating a new one.
